export { default as HomePage } from './HomePage'
export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as AdminLoginPage } from './AdminLoginPage'
export { default as AdminRegisterPage } from './AdminRegisterPage'
