CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nik VARCHAR(50) UNIQUE NULL,
  name VARCHAR(100) NOT NULL,
  username VARCHAR(50) UNIQUE NULL,
  email VARCHAR(100) UNIQUE NULL,
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(20) UNIQUE NULL,
  role ENUM('Admin', 'Pimpinan', 'Staf', 'Nasabah') DEFAULT 'Nasabah',
  refresh_token TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
